/*
 * CIReportPage.java
 *
 * Created on September 2, 2013, 2:10 PM
 */

package com.rameses.clfc.loan.views;

import com.rameses.osiris2.themes.OKCancelPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author  Rameses
 */
@StyleSheet
@Template(OKCancelPage.class)
public class CIReportPage extends javax.swing.JPanel {
    
    /** Creates new form CIReportPage */
    public CIReportPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xLabel4 = new com.rameses.rcp.control.XLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        setPreferredSize(new java.awt.Dimension(425, 325));
        setLayout(new java.awt.BorderLayout());

        xLabel4.setFontStyle("font-weight:bold;");
        xLabel4.setPadding(new java.awt.Insets(1, 0, 1, 1));
        xLabel4.setPreferredSize(new java.awt.Dimension(95, 20));
        xLabel4.setText("Evaluation");
        add(xLabel4, java.awt.BorderLayout.NORTH);

        xTextArea1.setCaption("Business Evaluation");
        xTextArea1.setName("entity.evaluation"); // NOI18N
        xTextArea1.setRequired(true);
        xTextArea1.setTextCase(com.rameses.rcp.constant.TextCase.UPPER);
        jScrollPane1.setViewportView(xTextArea1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
