/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.clfc.treasury.ledger.amnesty.smc.handler;

/**
 *
 * @author cebu01
 */
public class DateTermHandlerPage extends javax.swing.JPanel {

    /**
     * Creates new form DateTermHandlerPage
     */
    public DateTermHandlerPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();

        setLayout(new java.awt.BorderLayout());

        xIntegerField1.setCaption("Year(s)");
        xIntegerField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        xIntegerField1.setName("action.year"); // NOI18N
        xIntegerField1.setPreferredSize(new java.awt.Dimension(100, 23));
        xFormPanel1.add(xIntegerField1);

        xComboBox1.setCaption("Month(s)");
        xComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        xComboBox1.setItems("monthList");
        xComboBox1.setName("action.month"); // NOI18N
        xComboBox1.setPreferredSize(new java.awt.Dimension(100, 23));
        xFormPanel1.add(xComboBox1);

        xComboBox2.setCaption("Day(s)");
        xComboBox2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        xComboBox2.setItems("daysList");
        xComboBox2.setName("action.day"); // NOI18N
        xComboBox2.setPreferredSize(new java.awt.Dimension(100, 23));
        xFormPanel1.add(xComboBox2);

        add(xFormPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    // End of variables declaration//GEN-END:variables
}
