/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.clfc.patch.loan.detail;

/**
 *
 * @author cebu01
 */
public class AppInfoPage extends javax.swing.JPanel {

    /**
     * Creates new form AppInfoPage
     */
    public AppInfoPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xPanel1 = new com.rameses.rcp.control.XPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xDecimalField1 = new com.rameses.rcp.control.XDecimalField();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xLookupField2 = new com.rameses.rcp.control.XLookupField();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Application");
        xPanel1.setBorder(xTitledBorder1);

        xFormPanel1.setCaptionWidth(110);

        xTextField2.setCaption("App. No.");
        xTextField2.setCaptionWidth(110);
        xTextField2.setName("entity.appno"); // NOI18N
        xTextField2.setPreferredSize(new java.awt.Dimension(200, 20));
        xTextField2.setRequired(true);
        xFormPanel1.add(xTextField2);

        xComboBox2.setCaption("App. Type");
        xComboBox2.setDynamic(true);
        xComboBox2.setExpression("${item.value}");
        xComboBox2.setItemKey("value");
        xComboBox2.setItems("appTypes");
        xComboBox2.setName("entity.apptype"); // NOI18N
        xComboBox2.setPreferredSize(new java.awt.Dimension(200, 23));
        xComboBox2.setRequired(true);
        xFormPanel1.add(xComboBox2);

        xComboBox1.setCaption("Loan Type");
        xComboBox1.setDynamic(true);
        xComboBox1.setItems("loanTypes");
        xComboBox1.setName("entity.loantype"); // NOI18N
        xComboBox1.setPreferredSize(new java.awt.Dimension(150, 23));
        xComboBox1.setRequired(true);
        xFormPanel1.add(xComboBox1);

        xDateField1.setCaption("Release Date");
        xDateField1.setCaptionWidth(110);
        xDateField1.setName("entity.dtreleased"); // NOI18N
        xDateField1.setOutputFormat("MMM-dd-yyyy");
        xDateField1.setPreferredSize(new java.awt.Dimension(200, 20));
        xDateField1.setRequired(true);
        xFormPanel1.add(xDateField1);

        xDecimalField1.setCaption("Amount Released");
        xDecimalField1.setCaptionWidth(110);
        xDecimalField1.setName("entity.loanamount"); // NOI18N
        xDecimalField1.setPreferredSize(new java.awt.Dimension(150, 20));
        xDecimalField1.setRequired(true);
        xFormPanel1.add(xDecimalField1);

        xTextField1.setCaption("Borrower");
        xTextField1.setCaptionWidth(110);
        xTextField1.setName("entity.borrower.name"); // NOI18N
        xTextField1.setPreferredSize(new java.awt.Dimension(350, 20));
        xTextField1.setRequired(true);
        xFormPanel1.add(xTextField1);

        xLookupField2.setCaption("Route");
        xLookupField2.setCaptionWidth(110);
        xLookupField2.setExpression("${entity.route.description}");
        xLookupField2.setHandler("routeLookupHandler");
        xLookupField2.setPreferredSize(new java.awt.Dimension(250, 20));
        xLookupField2.setRequired(true);
        xFormPanel1.add(xLookupField2);

        xLookupField1.setCaption("Product Type");
        xLookupField1.setCaptionWidth(110);
        xLookupField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        xLookupField1.setExpression("${entity.producttype.name}");
        xLookupField1.setHandler("productTypeLookup");
        xLookupField1.setPreferredSize(new java.awt.Dimension(200, 20));
        xLookupField1.setRequired(true);
        xFormPanel1.add(xLookupField1);

        javax.swing.GroupLayout xPanel1Layout = new javax.swing.GroupLayout(xPanel1);
        xPanel1.setLayout(xPanel1Layout);
        xPanel1Layout.setHorizontalGroup(
            xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addContainerGap())
        );
        xPanel1Layout.setVerticalGroup(
            xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XDecimalField xDecimalField1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XLookupField xLookupField2;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    // End of variables declaration//GEN-END:variables
}
